--Database complete tree After this is queried run inserts.sql file

CREATE TABLE IF NOT EXISTS categories(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> '')
);

CREATE TABLE IF NOT EXISTS sub_categories(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    cat_id integer REFERENCES categories(id)
);

CREATE TABLE IF NOT EXISTS commerce_types(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK ( name <> '' )
);

CREATE TABLE IF NOT EXISTS product_types(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar NOT NULL CHECK ( name <> '' ),
    subcat_id integer REFERENCES sub_categories(id)
);

CREATE TABLE IF NOT EXISTS commerces(
    id SERIAL PRIMARY KEY,
    name text NOT NULL CHECK (name <> ''),
    logo text,
    lat float,
    lng float,
    geohash varchar,
    type_id integer REFERENCES commerce_types(id),
    precios_cuidados boolean DEFAULT false,
    tarjeta_alimentar BOOLEAN DEFAULT false,
);

CREATE TABLE IF NOT EXISTS products (
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	presentation TEXT,
	brand TEXT,
	precios_cuidados BOOLEAN DEFAULT FALSE,
	oferta_temporal BOOLEAN DEFAULT FALSE,
	product_type_id interger REFERENCES product_types(id)
);

CREATE TABLE IF NOT EXISTS prices (
    id SERIAL PRIMARY KEY,
    value FLOAT NOT NULL,
    product_id integer REFERENCES products(id),
    commerce_id integer REFERENCES commerces(id),
    created_at date DEFAULT NOW(),
    updated_at date DEFAULT NOW(),
    expires_at date DEFAULT NOW()
);










