--Database complete tree

CREATE TABLE IF NOT EXISTS categories(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> '')
);

CREATE TABLE IF NOT EXISTS sub_categories(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    cat_id integer REFERENCES categories(id)
);

CREATE TABLE IF NOT EXISTS commerce_types(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK ( name <> '' )
);

CREATE TABLE IF NOT EXISTS product_types(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar NOT NULL CHECK ( name <> '' ),
    subcat_id integer REFERENCES sub_categories(id)
);

CREATE TABLE IF NOT EXISTS commerces(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    logo text,
    lat float,
    lng float,
    geohash varchar,
    type integer REFERENCES commerce_types(id),
    owner text,
    city text
);

CREATE TABLE IF NOT EXISTS products(
    id integer PRIMARY KEY,
    presentation text NOT NULL CHECK (presentation <> ''),
    img text NOT NULL,
    brand text NOT NULL CHECK (brand <> ''),
    cat_id integer REFERENCES categories(id),
    subcat_id integer REFERENCES sub_categories(id),
    type_id INTEGER REFERENCES product_types(id)
);

CREATE TABLE IF NOT EXISTS prices(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id integer REFERENCES products(id),
    commerce_id integer REFERENCES commerces(id),
    price float NOT NULL,
    geohash varchar
);









